// AUTH_USER
export const GET_ALL_MOVIES = "CONTENT_USER_LIST";
export const GET_COMMING = "GET_COMMING";
export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const GET_TOP_RATED = "GET_TOP_RATED";
export const GET_DETAIL_MOVIES = "CREATE_USERS";
export const GET_REQ_SEARCH = "GET_REQ_SEARCH";
export const GET_AUTOCOMPLETE = "GET_AUTOCOMPLETE";
export const GET_SIMILAR_MOVIES = "GET_SIMILAR_MOVIES";
export const GET_GENRE_MOVIES = "GET_GENRE_MOVIES";
